<a href="https://colab.research.google.com/github/momonts/DSA58011/blob/main/FinalProject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np

#Input sudoku problem
grid = [[5, 3, 0, 0, 7, 0, 0, 0, 0],
        [6, 0, 0, 1, 9, 5, 0, 0, 0],
        [0, 9, 8, 0, 0, 0, 0, 6, 0],
        [8, 0, 0, 0, 6, 0, 0, 0, 3],
        [4, 0, 0, 8, 0, 3, 0, 0, 1],
        [7, 0, 0, 0, 2, 0, 0, 0, 6],
        [0, 6, 0, 0, 0, 0, 2, 8, 0],
        [0, 0, 0, 4, 1, 9, 0, 0, 5],
        [0, 0, 0, 0, 8, 0, 0, 7, 9]]

#Checking possible numbers
def psbl(row, col, num):
  global grid

#Check the numbers present in a row
  for i in range(0,9):
    if grid[row][i] == num:
      return False  

#Check the numbers present in a col
  for i in range(0,9):
    if grid[i][col] == num:
      return False

#Check the numbers present in a 3x3 grid
  x0 = (col // 3) * 3
  y0 = (row // 3) * 3

  for i in range(0,3):
    for j in range(0,3):
      if grid[y0+1][x0+1] == num:
        return False

  return True

#Solving
def slv():
  global grid
  for row in range(0,9):
    for col in range(0,9):
      if grid[row][col] == 0:
        for num in range(1,10):
          if psbl(row, col, num):
            grid[row][col] = num
            slv()
            grid[row][col] = 0
          
        return


  print("[SOLUTION]\n\n", np.matrix(grid))
  input('\n\n Press ENTER for more solution \n\n')

slv()

[SOLUTION]

 [[5 3 2 6 7 1 8 9 4]
 [6 2 3 1 9 5 7 4 8]
 [1 9 8 3 4 7 5 6 2]
 [8 1 9 7 6 2 4 5 3]
 [4 7 6 8 5 3 9 2 1]
 [7 4 5 9 2 8 3 1 6]
 [9 6 1 5 3 4 2 8 7]
 [2 8 7 4 1 9 6 3 5]
 [3 5 4 2 8 6 1 7 9]]


 Press ENTER for more solution 


[SOLUTION]

 [[5 3 2 6 7 1 8 9 4]
 [6 2 3 1 9 5 7 4 8]
 [1 9 8 3 4 7 5 6 2]
 [8 1 9 7 6 2 4 5 3]
 [4 7 6 8 5 3 9 2 1]
 [7 5 4 9 2 8 3 1 6]
 [9 6 1 5 3 4 2 8 7]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]


 Press ENTER for more solution 


[SOLUTION]

 [[5 3 2 6 7 1 8 9 4]
 [6 2 3 1 9 5 7 4 8]
 [1 9 8 3 4 7 5 6 2]
 [8 4 9 7 6 2 1 5 3]
 [4 7 6 8 5 3 9 2 1]
 [7 5 4 9 2 8 3 1 6]
 [9 6 1 5 3 4 2 8 7]
 [2 8 7 4 1 9 6 3 5]
 [3 1 5 2 8 6 4 7 9]]


 Press ENTER for more solution 


[SOLUTION]

 [[5 3 2 6 7 1 8 9 4]
 [6 2 3 1 9 5 7 4 8]
 [1 9 8 3 4 7 5 6 2]
 [8 5 9 7 6 2 4 1 3]
 [4 7 6 8 5 3 9 2 1]
 [7 1 4 9 2 8 3 5 6]
 [9 6 1 5 3 4 2 8 7]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]


 Press ENTER for more solution 


[SOLUTION]

 [[5 3 2 6 7 1 8 9 4]
 [6 2 7 1 

KeyboardInterrupt: ignored